StudentHelp/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='home'),
    path('create/', views.create_user, name='create_user'),
    path('index/', views.index, name='index'),
    path('profilepage/', views.profile_page, name='profile_page'),
    path('post/', views.post_list, name='post_list'),
    path('createPost/', views.create_post, name='create_post'),
    path('postDetail/<int:post_id>/', views.post_detail, name='post_detail'),
    path('updatePost/<int:post_id>/', views.update_post, name='update_post'),
    path('deletePost/<int:post_id>/', views.delete_post, name='delete_post'),
    path('postComment/<int:post_id>/', views.post_comment, name='post_comment'),
    path('addComment/<int:post_id>/', views.add_comment, name='add_comment'),
    path('like-post/<int:post_id>/', views.like_post, name='like_post'),
     path('request-transport/<int:post_id>/', views.request_transport, name='request_transport'),
      path('transport_requests/<int:post_id>/', views.transport_requests, name='transport_requests'),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path ,  include
from django.contrib import admin, auth
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
     path('StudentHelp/', include('StudentHelp.urls')),
        path('accounts/', include('django.contrib.auth.urls')),
        path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'), name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='registration/logout.html'), name ='logout'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

StudentHelp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nom = models.CharField(max_length=50, default='')
    prenom = models.CharField(max_length=50, default='')
    image = models.ImageField(upload_to='images/')
    telephone = models.CharField(max_length=20)

class Post(models.Model):
    POST_TYPES = (
        ('Stage', 'Stage'),
        ('Logement', 'Logement'),
        ('Transport', 'Transport'),
        ('Recommandation', 'Recommandation'),
        ('Evenement', 'Evenement'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')
    post_type = models.CharField(max_length=50, choices=POST_TYPES)
    date = models.DateField()
    likes = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if not self.date:
            self.date = timezone.now().date()

        if self.post_type == 'Evenement':
            if not hasattr(self, 'evenement'):

                evenement = Evenement.objects.create()
                self.evenement = evenement

        super().save(*args, **kwargs)


class Recommandation(models.Model):
    post = models.OneToOneField(Post, on_delete=models.CASCADE)
    text = models.TextField()

class Reaction(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    like = models.BooleanField(default=False)

class Evenement(Post):
    intitule = models.CharField(max_length=100)
    description = models.TextField()
    lieu = models.CharField(max_length=100)
    contact_info = models.CharField(max_length=100)

    EVENT_SUBTYPES = (
        ('EvenClub', 'EvenClub'),
        ('EventSocial', 'EventSocial'),
    )

    subtype = models.CharField(max_length=50, choices=EVENT_SUBTYPES, null=True, default=None)


class Stage(Post):
    typeStg = models.IntegerField()
    societe = models.CharField(max_length=100)
    duree = models.IntegerField()
    subject = models.CharField(max_length=255 , default='')
    contactInfo = models.CharField(max_length=100)

class Logement(models.Model):
    localisation = models.CharField(max_length=100)
    description = models.TextField()
    contactInfo = models.CharField(max_length=100)
    post = models.OneToOneField(Post, on_delete=models.CASCADE , default='')

class Transport(models.Model):
    depart = models.CharField(max_length=100)
    destination = models.CharField(max_length=100)
    heure_dep = models.TimeField()
    nbreSieges = models.IntegerField()
    contactInfo = models.CharField(max_length=100)
    post = models.OneToOneField(Post, on_delete=models.CASCADE , default='')


class EvenClub(models.Model):
    evenement = models.ForeignKey(Evenement, on_delete=models.CASCADE)
    club = models.CharField(max_length=100)

class EventSocial(models.Model):
    evenement = models.ForeignKey(Evenement, on_delete=models.CASCADE)
    prix = models.FloatField()


class TransportRequest(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)

StudentHelp/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User

class CustomUserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = UserProfile
        fields = ('nom', 'prenom', 'image', 'telephone')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user_profile = super().save(commit=False)
        password = self.cleaned_data.get("password1")
        if password:
            user = User.objects.create_user(username=user_profile.nom, password=password)
            user_profile.user = user
        if commit:
            user_profile.save()
        return user_profile


from .models import Post, Evenement

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image', 'post_type', 'date']

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        if 'post_type' in self.fields:
            self.fields['post_type'].choices = [(choice[0], choice[1]) for choice in Post.POST_TYPES]
        if 'post_type' in self.initial and self.initial['post_type'] == 'Evenement':
            self.fields['subtype'] = forms.ChoiceField(choices=Evenement.EVENT_SUBTYPES)
        elif 'subtype' in self.fields:
            del self.fields['subtype']

from django import forms
from .models import TransportRequest

class TransportRequestForm(forms.ModelForm):
    class Meta:
        model = TransportRequest
        fields = ['name', 'phone_number']

StudentHelp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .forms import CustomUserCreationForm
from .models import UserProfile , Transport ,  Recommandation , Evenement , Stage , Logement

def create_user(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'User created successfully!')
            return redirect('profile_page')
    else:
        form = CustomUserCreationForm()
    return render(request, 'create_user.html', {'form': form})

from .models import TransportRequest
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import UserProfile

@login_required
def index(request):
    pending_requests = TransportRequest.objects.filter(post__user=request.user).exists()
    transport_requests = TransportRequest.objects.filter(post__user=request.user)
    return render(request, 'index.html', {'pending_requests': pending_requests, 'transport_requests': transport_requests})

@login_required
def profile_page(request):
    user_profile = UserProfile.objects.get(user=request.user)
    return render(request, 'profilepage.html', {'user_profile': user_profile})


@login_required
def post_list(request):
    post_type = request.GET.get('post_type')
    if post_type:
        posts = Post.objects.filter(post_type=post_type).order_by('-date')
    else:
        posts = Post.objects.all().order_by('-date')

    user_profile = UserProfile.objects.get(user=request.user)
    return render(request, 'post_list.html', {'posts': posts, 'user_profile': user_profile})

def profile_view(request, user_id):
    user_profile = get_object_or_404(UserProfile, pk=user_id)
    return render(request, 'profile_page.html', {'user_profile': user_profile})
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Post, UserProfile
from .forms import PostForm

from django.db import transaction

from datetime import date

from datetime import date
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Post

@login_required
def create_post(request):
    if request.method == 'POST':
        post_type = request.POST.get('post_type')
        image = request.FILES.get('image')
        date_posted = request.POST.get('date')
        post = Post.objects.create(
            user=request.user,
            image=image,
            post_type=post_type,
            date=date_posted if date_posted else date.today()
        )
        if post_type in ['Evenement', 'Stage']:
            pass
        elif post_type == 'Logement':
            localisation = request.POST.get('localisation')
            description = request.POST.get('description_logement')
            contactInfo_logement = request.POST.get('contactInfo_logement')

            logement = Logement.objects.create(
                post=post,
                localisation=localisation,
                description=description,
                contactInfo=contactInfo_logement
            )

        elif post_type == 'Transport':
            depart = request.POST.get('depart')
            destination = request.POST.get('destination')
            heure_dep = request.POST.get('heure_dep')
            nbreSieges = request.POST.get('nbreSieges')
            contactInfo_transport = request.POST.get('contactInfo_transport')

            transport = Transport.objects.create(
                post=post,
                depart=depart,
                destination=destination,
                heure_dep=heure_dep,
                nbreSieges=nbreSieges,
                contactInfo=contactInfo_transport
            )

        elif post_type == 'Recommandation':
            text = request.POST.get('text')

            recommandation = Recommandation.objects.create(
                post=post,
                text=text
            )

        return redirect('post_detail', post_id=post.id)
    else:
        user_profile = UserProfile.objects.get(user=request.user)
        return render(request, 'create_post.html', {'user_profile': user_profile})




from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Post, UserProfile
from .forms import PostForm

@login_required
def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    user_profile = UserProfile.objects.get(user=request.user)
    return render(request, 'post_detail.html', {'post': post, 'user_profile': user_profile})


@login_required
def update_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            if post.post_type == 'Evenement':
                post.evenement.subtype = request.POST.get('subtype', None)
            post.save()
            messages.success(request, 'Post updated successfully!')
            return redirect('post_detail', post_id=post.id)
    else:
        form = PostForm(instance=post)
    return render(request, 'update_post.html', {'form': form, 'post': post})

@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        post.delete()
        messages.success(request, 'Post deleted successfully!')
        return redirect('post_list')
    return render(request, 'delete_post.html', {'post': post})


from django.shortcuts import render, redirect
from .models import Post, Reaction

def post_comment(request, post_id):
    post = Post.objects.get(pk=post_id)
    comments = Reaction.objects.filter(post=post)
    user_profile = None
    if request.user.is_authenticated:
        try:
            user_profile = request.user.userprofile
        except UserProfile.DoesNotExist:
            pass

    return render(request, 'post_comment.html', {'post': post, 'comments': comments, 'user_profile': user_profile})

def add_comment(request, post_id):
    if request.method == 'POST':
        post = Post.objects.get(pk=post_id)
        comment_text = request.POST.get('comment')
        user = request.user
        if comment_text:
            reaction = Reaction.objects.create(post=post, user=user, comment=comment_text)
    return redirect('post_comment', post_id=post_id)


from django.http import HttpResponseRedirect

def like_post(request, post_id):
    if request.method == 'POST':
        post = get_object_or_404(Post, pk=post_id)
        liked_posts = request.session.get('liked_posts', [])
        if post_id in liked_posts:
            liked_posts.remove(post_id)
            post.likes -= 1
        else:
            liked_posts.append(post_id)
            post.likes += 1
        request.session['liked_posts'] = liked_posts
        post.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/') + '#post' + str(post_id))


from django.shortcuts import render, redirect
from .models import TransportRequest
from .forms import TransportRequestForm

def request_transport(request, post_id):
    if request.method == 'POST':
        form = TransportRequestForm(request.POST)
        if form.is_valid():
            transport_request = form.save(commit=False)
            transport_request.post_id = post_id
            transport_request.save()
            return redirect('post_list')
    else:
        form = TransportRequestForm()
    return render(request, 'transport_request_form.html', {'form': form})

@login_required
def transport_requests(request, post_id):
    user_profile = UserProfile.objects.get(user=request.user)
    transport_requests = TransportRequest.objects.filter(post_id=post_id)
    return render(request, 'transport_requests.html', {'transport_requests': transport_requests, 'user_profile': user_profile})

StudentHelp/templates/create_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create User</title>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <style>
        body {
            background-color: #f8f9fa;
            font-family: Arial, sans-serif;
        }

        .container {
            max-width: 500px;
            margin: 50px auto;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0,0,0,0.1);
            padding: 40px;
            background-color: #fff;
        }

        h2 {
            color: #007bff;
            text-align: center;
            margin-bottom: 30px;
        }

        .form-group {
            margin-bottom: 25px;
        }

        label {
            font-weight: bold;
        }

        input[type="text"],
        input[type="password"],
        input[type="tel"],
        input[type="file"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ced4da;
            border-radius: 5px;
        }

        .btn-create {
            background-color: #007bff;
            border-color: #007bff;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 5px;
            width: 100%;
        }

        .btn-create:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }

        .text-danger {
            color: #dc3545;
            font-size: 14px;
        }

        .messages {
            margin-bottom: 20px;
        }

        .alert {
            padding: 10px 20px;
            margin-bottom: 10px;
            border-radius: 5px;
        }

        .alert-success {
            background-color: #d4edda;
            border-color: #c3e6cb;
            color: #155724;
        }

        .alert-danger {
            background-color: #f8d7da;
            border-color: #f5c6cb;
            color: #721c24;
        }
    </style>
</head>
<body>
<div class="container">
    <h2>Create an Account</h2>

    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_nom">Nom</label>
            {{ form.nom }}
            {% for error in form.nom.errors %}
                <p class="text-danger">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="form-group">
            <label for="id_prenom">Prénom</label>
            {{ form.prenom }}
            {% for error in form.prenom.errors %}
                <p class="text-danger">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="form-group">
            <label for="id_password1">Password</label>
            {{ form.password1 }}
            {% for error in form.password1.errors %}
                <p class="text-danger">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="form-group">
            <label for="id_password2">Confirm Password</label>
            {{ form.password2 }}
            {% for error in form.password2.errors %}
                <p class="text-danger">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="form-group">
            <label for="id_image">Image</label>
            {{ form.image }}
            {% for error in form.image.errors %}
                <p class="text-danger">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="form-group">
            <label for="id_telephone">Téléphone</label>
            {{ form.telephone }}
            {% for error in form.telephone.errors %}
                <p class="text-danger">{{ error }}</p>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary btn-create">Create</button>
    </form>
</div>


<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

StudentHelp/templates/delete_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Post</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mt-5">
                    <div class="card-header">
                        Confirm Deletion
                    </div>
                    <div class="card-body">
                        <p>Are you sure you want to delete this post?</p>
                        <form method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Delete</button>
                            <a href="{% url 'post_detail' post_id=post.id %}" class="btn btn-secondary">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

StudentHelp/templates/post_comment.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Page Title</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .blue-text {
            color: blue;
        }
    </style>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container">
        <h1 class="mt-4 mb-4">{{ post }}</h1>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card mb-4">

                    <div class="card-header">
                        <div class="d-flex align-items-center">
                            <img src="{{ post.user.userprofile.image.url }}" class="rounded-circle mr-2" width="40" height="40" alt="User Image">
                            <span class="font-weight">{{ post.user.userprofile.nom }} {{ post.user.userprofile.prenom }}</span>
                        </div>
                    </div>
                    <img src="{{ post.image.url }}" class="card-img-top" alt="Post Image">
                    <div class="card-body">
                        <h2 class="card-title">
                            {% if post.post_type == 'Stage' %}
                                {{ post.subject }}
                            {% elif post.post_type == 'Logement' %}
                                {{ post.localisation }}
                            {% elif post.post_type == 'Transport' %}
                                From: {{ post.depart }} - To: {{ post.destination }}
                            {% elif post.post_type == 'Recommandation' %}
                                Recommendation
                            {% elif post.post_type == 'Evenement' %}
                                {{ post.intitule }} at {{ post.lieu }}
                            {% endif %}
                        </h2>
                        <p class="card-text text-muted">{{ post.date }}</p>
                        <p class="card-text">{{ post.description }}</p>
                    </div>
                </div>
                <div class="card mb-4">
                    <div class="card-header">
                        Comments
                    </div>
                    <div class="card-body" id="comments">
                        {% for comment in comments %}
                        <div class="media mb-3">
                            <img src="{{ comment.user.userprofile.image.url }}" class="mr-3 rounded-circle" width="40" height="40" alt="User Image">
                            <div class="media-body">
                                <h5 class="mt-0">{{ comment.user.username }} </h5>
                                <span class="comment-text">{{ comment.comment }}</span>
                            </div>
                        </div>
                        {% endfor %}
                        <form method="post" action="{% url 'add_comment' post.id %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="comment">Add Comment:</label>
                                <textarea class="form-control" id="comment" name="comment" rows="3"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function() {
            var commentTexts = document.querySelectorAll('.comment-text');
            commentTexts.forEach(function(element) {
                var words = element.textContent.split(' ');
                for (var i = 0; i < words.length; i++) {
                    if (words[i].startsWith('@')) {
                        words[i] = '<span class="blue-text">' + words[i] + '</span>';
                    }
                }
                element.innerHTML = words.join(' ');
            });
        });
    </script>
</body>

</html>

StudentHelp/templates/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Posts</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">
        <h1 class="mt-4">My Posts</h1>
        {% for post in user_profile.user.post_set.all %}
            <div class="card my-3">
                <div class="card-body">
                    <h5 class="card-title">{{ post }}</h5>
                    <p class="card-text">Post Type: {{ post.post_type }}</p>
                    <p class="card-text">Date: {{ post.date }}</p>
                    <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post }}" style="max-width: 200px;">
                    {% if post.post_type == 'Evenement' %}
                        <p class="card-text">Event Subtype: {{ post.evenement.get_subtype_display }}</p>
                    {% endif %}
                    <a href="{% url 'update_post' post_id=post.id %}" class="btn btn-primary mr-2">Update</a>
                    <a href="{% url 'delete_post' post_id=post.id %}" class="btn btn-danger">Delete</a>
                </div>
                <div class="text-center">
                    <button class="btn btn-primary like-btn" data-post-id="{{ post.id }}"><i class="far fa-thumbs-up"></i> Like</button>
                    <span id="likesCount{{ post.id }}">{{ post.likes }}</span>
                    <a href="{% url 'post_comment' post.id %}" class="btn btn-secondary"><i class="far fa-comment"></i>.  Comments</a>
                </div>
            </div>
        {% empty %}
            <p>No posts found.</p>
        {% endfor %}
        <a href="{% url 'post_list' %}" class="btn btn-success">OK</a>
    </div>
</body>
</html>

StudentHelp/templates/profilepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Profile</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        body {
            margin-top: 70px;
            color: #1a202c;
            text-align: left;
            background-color: #e2e8f0;
        }
        .main-body {
            padding: 15px;
        }
        .profile-image {
            width: 150px;
            height: 150px;
            object-fit: cover;
            border-radius: 50%;
        }
        .user-info {
            text-align: center;
            margin-top: 20px;
        }
        .user-info h4 {
            margin-bottom: 0;
        }
        .user-info p {
            margin-top: 5px;
        }
        .post-card {
            margin-bottom: 20px;
        }
        .post-buttons {
            margin-top: 10px;
        }
    </style>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">
        <div class="main-body">
            <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                <img src="{{ user_profile.image.url }}" alt="Profile Image" class="rounded-circle profile-image">
                                <div class="user-info">
                                    <h4>{{ user_profile.nom }} {{ user_profile.prenom }}</h4>
                                    <p>Phone number : {{ user_profile.telephone }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-8">
                    {% for post in user_profile.user.post_set.all %}
                        <div class="card post-card">
                            <img src="{{ post.image.url }}" alt="Post Image" class="card-img-top">
                            <div class="card-body">
                                <h5 class="card-title">{{ post }}</h5>
                                <p class="card-text">Post Type: {{ post.post_type }}</p>
                                <div class="post-buttons">
                                    <a href="{% url 'update_post' post_id=post.id %}" class="btn btn-primary">Update</a>
                                    <a href="{% url 'delete_post' post_id=post.id %}" class="btn btn-danger">Delete</a>
                                    {% if post.post_type == 'Transport' %}
                                        {% if post.transportrequest_set.all %}
                                            <a href="{% url 'transport_requests' post_id=post.id %}" class="btn btn-info">View Transport Requests</a>
                                        {% endif %}
                                    {% endif %}
                                </div>
                                <div class="text-center">
                                    <button class="btn btn-primary like-btn" data-post-id="{{ post.id }}"><i class="far fa-thumbs-up"></i> Like</button>
                                    <span id="likesCount{{ post.id }}">{{ post.likes }}</span>
                                    <a href="{% url 'post_comment' post.id %}" class="btn btn-secondary"><i class="far fa-comment"></i>.  Comments</a>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <p>No posts found.</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</body>
</html>